version: 2.0

jobs:
  build-code:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build Source Code
          command: |
            echo "Build Start"
            make
            echo "Build End"

  unit-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Run Unit Test
          command: |
            source sourceme
            cytest -d tests


workflows:
  version: 2
  Build:
    jobs:
      - build-code
  Unit Test:
    jobs:
      - unit-test
