version: 2.0

jobs:
  checkout:
    docker:
      - image: aloknigam247/cygnus
    working_directory: ~/cygnus
    steps:
      - checkout
      - run:
          name: Initial setup
          command: |
            cd ~/cygnus
            mkdir logs
            mkdir reports
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus

  release-tests:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Release Build (Strict)
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --strict --release
      - run:
          name: Run Tests
          command: |
            cd ~/cygnus
            source sourceme
            cyregress -a -d tests
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports

  mem-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Debug Build (Strict)
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --strict --debug
      - run:
          name: Memory Checks
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --memory
            cyregress -a -d tests --mem-check 2>&1 | tee reports/mem-checks.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports
  
  sanitization:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Sanitization Checks
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --sanitize
            cyregress -a -d tests --sanitize 2>&1 | tee reports/sanitization.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports
  
  coverage:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Coverage Build
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --coverage
      - run:
          name: Coverage Run
          command: |
            cd ~/cygnus
            source sourceme
            cyregress -a -d tests --coverage
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports

  performance:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Performance Build
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --perf
      - run:
          name: Performance Checks
          command: |
            cd ~/cygnus
            source sourceme
            cyregress -a -d tests --perf 2>&1 | tee reports/perf.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports

  lint-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Run
          command: |
            cd ~/cygnus
            source sourceme
            cppcheck --enable=all src 2>&1 | tee reports/lint.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports

  docs-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate Docs
          command: |
            cd ~/cygnus
            source sourceme
            gen-docs
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports

  style-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Source Code Style Check
          command: |
            cd ~/cygnus
            source sourceme
            style-check src | tee reports/style.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports

  gen-reports:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Report Generation
          command: |
              cd ~
              source cygnus/sourceme
              gen-report | tee reports/report.log
      - store_artifacts:
          path: ~/logs
          destination: Logs
      - store_artifacts:
          path: ~/reports
          destination: Reports

workflows:
  version: 2
  Commit-Regression:
    jobs:
      - checkout
      - release-tests:
          requires:
            - checkout
      - mem-checks:
          requires:
            - checkout
      - sanitization:
          requires:
            - checkout
      - coverage:
          requires:
            - checkout
      - performance:
          requires:
            - checkout
      - lint-checks:
          requires:
            - checkout
      - docs-checks:
          requires:
            - checkout
      - style-checks:
          requires:
            - checkout
      - gen-report:
          requires:
            - release-tests
            - mem-checks
            - sanitization
            - coverage
            - performance
            - lint-checks
            - docs-checks
            - style-checks
