version: 2.0

jobs:
  build-code:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build Source Code
          command: |
            echo "Build Start"
            make
            echo "Build End"
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  unit-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Unit Test
          command: |
            cd ~/project
            source sourceme
            cytest -d tests


workflows:
  version: 2
  Build:
    jobs:
      - build-code
      - unit-test:
          requires:
            - build-code
