version: 2.0

jobs:
  checkout:
    docker:
      - image: aloknigam247/cygnus
    working_directory: ~/cygnus
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus

  comp-warnings:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Compiler Warnings on strict mode
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --strict --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports
      - store_artifacts:
          path: ~/cygnus/build.log
          destination: Build log
      - store_artifacts:
          path: ~/cygnus/reports/warnings/warns
          destination: Warnings

  func-tests:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Unit Test
          command: |
            cd ~/cygnus
            source sourceme
            cyregress -d tests -a 2>&1 | tee unittest.log
      - store_artifacts:
          path: ~/cygnus/cyregress.log
          destination: unit-test-log
  
  unit-tests:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Unit Test
          command: |
            cd ~/cygnus
            source sourceme
            cyregress -d tests -a 2>&1 | tee unittest.log
      - store_artifacts:
          path: ~/cygnus/cyregress.log
          destination: unit-test-log
  
  perf-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/

  mem-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/

  unit-cov:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Coverage Run
          command: |
              cd ~/cygnus
              source sourceme
              cyregress -a -d tests --coverage
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports
      - store_artifacts:
          path: ~/cygnus/reports/cov
          destination: Coverage data

  func-cov:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Coverage Run
          command: |
              cd ~/cygnus
              source sourceme
              cyregress -a -d tests --coverage
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports
      - store_artifacts:
          path: ~/cygnus/reports/cov
          destination: Coverage data

  lint-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Run
          command: echo "Disabled"

  docs-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate Docs
          command: |
            cd ~/cygnus
            source sourceme
            gen-docs
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports
      - store_artifacts:
          path: ~/cygnus/docs
          destination: Docs
      - store_artifacts:
          path: ~/cygnus/reports/docs/undocumented
          destination: Doc Coverage

  code-style:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/

  report-gen:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Report Generation
          command: |
              cd ~
              source cygnus/sourceme
              gen-report | tee report.log

workflows:
  version: 2
  Commit-Regression:
    jobs:
      - checkout
      - comp-warnings:
          requires:
            - checkout
      - func-tests:
          requires:
            - comp-warnings
      - func-cov:
          requires:
            - comp-warnings
      - unit-tests:
          requires:
            - checkout
      - perf-checks:
          requires:
            - checkout
      - mem-checks:
          requires:
            - checkout
      - unit-cov:
          requires:
            - checkout
      - lint-checks:
          requires:
            - checkout
      - docs-checks:
          requires:
            - checkout
      - code-style:
          requires:
            - checkout
      - report-gen:
          requires:
            - func-tests
            - func-cov
            - unit-tests
            - unit-cov
            - perf-checks
            - mem-checks
            - lint-checks
            - docs-checks
            - code-style
