version: 2.0

jobs:
  build-code:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/cygnus
    steps:
      - checkout
      - run:
          name: Build Source Code
          command: |
            echo "Build Start"
            make | tee make.log 2>&1
            echo "Build End"
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: make.log
          destination: build-log

  unit-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Unit Test
          command: |
            cd ~/cygnus
            source sourceme
            cytest -d tests -a  | tee cytest.log 2>&1
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - cytest.log
      - store_artifacts:
          path: cytest.log
          destination: unit-test-log


workflows:
  version: 2
  Build:
    jobs:
      - build-code
      - unit-test:
          requires:
            - build-code
