version: 2.0

jobs:
  build-code:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Build Source Code
          command: |
            echo "Build Start"
            make
            echo "Build End"
      - persist_to_workspace:
          root: /
          paths:
            - tmp

  unit-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Run Unit Test
          command: |
            cd /tmp
            source sourceme
            cytest -d tests


workflows:
  version: 2
  Build:
    jobs:
      - build-code
  Unit Test:
    jobs:
      - unit-test
