version: 2.0

jobs:
  checkout:
    docker:
      - image: aloknigam247/cygnus
    working_directory: ~/cygnus
    steps:
      - checkout
      - run:
          name: Initial setup
          command: |
              cd ~/cygnus
              mkdir logs
              mkdir reports
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus

  release-warnings:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Compiler Warnings on strict mode
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --strict --release 2>&1 | tee logs/release_warnings.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus

  tests:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Unit Test
          command: |
            cd ~/cygnus
            source sourceme
            cyregress -a -d tests 2>&1 | tee reports/tests.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports

  debug-warnings:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Compiler Warnings on strict mode
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --strict --debug 2>&1 | tee logs/debug_warnings.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus

  mem-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Memory Checks
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --memory 2>&1 | tee logs/memory_build.log
              cyregress -a -d tests --mem-check 2>&1 | tee reports/mem-checks.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports
  
  sanitization:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Memory Checks
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --sanitize 2>&1 | tee logs/sanitize_build.log
              cyregress -a -d tests --sanitize 2>&1 | tee reports/sanitization.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports
  
  coverage:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Coverage Run
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --coverage 2>&1 | tee logs/coverage_build.log
              cyregress -a -d tests --coverage 2>&1 | tee reports/coverage.log 
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports

  performance:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Memory Checks
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --perf 2>&1 | tee logs/perf_build.log
              cyregress -a -d tests --perf 2>&1 | tee reports/perf.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - logs
            - reports

  lint-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Run
          command: |
              cd ~/cygnus
              source sourceme
              cppcheck --enable=all -I include src 2>&1 | tee reports/lint
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports

  docs-checks:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate Docs
          command: |
            cd ~/cygnus
            source sourceme
            gen-docs
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports

  style-check:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Source Code Style Check
          command: |
              cd ~/cygnus
              source sourceme
              style-check src | tee reports/style
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports

  report-gen:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Report Generation
          command: |
              cd ~
              source cygnus/sourceme
              gen-report | tee report.log
      - store_artifacts:
          path: ~/logs
          destination: Logs
      - store_artifacts:
          path: ~/reports
          destination: Reports

workflows:
  version: 2
  Commit-Regression:
    jobs:
      - checkout
      - release-warnings:
          requires:
            - checkout
      - tests:
          requires:
            - release-warnings
      - debug-warnings:
          requires:
            - checkout
      - mem-checks:
          requires:
            - debug-warnings
      - sanitization:
          requires:
            - checkout
      - coverage:
          requires:
            - checkout
      - performance:
          requires:
            - checkout
      - lint-checks:
          requires:
            - checkout
      - docs-checks:
          requires:
            - checkout
      - style-checks:
          requires:
            - checkout
      - report-gen:
          requires:
            - tests
            - mem-checks
            - sanitization
            - coverage
            - performance
            - lint-checks
            - docs-checks
            - style-checks
