version: 2.0

jobs:
  checkout:
    docker:
      - image: aloknigam247/cygnus
    working_directory: ~/cygnus
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus

  build-release:
    docker:
      - image: aloknigam247/cygnus
    working_directory: ~/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Release Build
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: build.log
          destination: build-log

  code-style:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/

  docs:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Generate Docs
          command: |
            cd ~/cygnus
            source sourceme
            gen-docs
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports
      - store_artifacts:
          path: ~/cygnus/docs
          destination: Docs
      - store_artifacts:
          path: ~/cygnus/reports/docs/undocumented
          destination: Doc Coverage

  unit-test:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Unit Test
          command: |
            cd ~/cygnus
            source sourceme
            cytest -d tests -a 2>&1 | tee unittest.log
      - store_artifacts:
          path: ~/cygnus/cytest.log
          destination: unit-test-log
  
  warnings:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Compiler Warnings on strict mode
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --strict --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports
      - store_artifacts:
          path: ~/cygnus/build.log
          destination: Build log
      - store_artifacts:
          path: ~/cygnus/reports/warnings/warns
          destination: Warnings

  lint:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Run
          command: echo "Disabled"

  coverage:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Coverage Run
          command: |
              cd ~/cygnus
              source sourceme
              cytest -a -d tests --coverage
      - persist_to_workspace:
          root: ~/cygnus
          paths:
            - reports
      - store_artifacts:
          path: ~/cygnus/reports/cov
          destination: Coverage data

  memory:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/

  performance:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/

  reports:
    docker:
      - image: aloknigam247/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Report Generation
          command: |
              cd ~/cygnus
              source sourceme
              gen-report | tee report.log

workflows:
  version: 2
  Commit-Test:
    jobs:
      - checkout
      - build-release:
          requires:
            - checkout
      - code-style:
          requires:
            - checkout
      - docs:
          requires:
            - checkout
      - warnings:
          requires:
            - build-release
      - unit-test:
          requires:
            - build-release
      - lint:
          requires:
            - warnings
      - coverage:
          requires:
            - build-release
      - memory:
          requires:
            - build-release
      - performance:
          requires:
            - build-release
      - reports:
          requires:
            - code-style
            - docs
            - unit-test
            - lint
            - coverage
            - memory
            - performance
