version: 2.0

jobs:
  source-code-build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build Source Code
          command: |
            echo "Build Start"
            make
            echo "Build End"

workflows:
  version: 2
  Regression:
    jobs:
      - source-code-build
