version: 2.0

jobs:
  checkout:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/cygnus
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus

  build-release:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build Release
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: build.log
          destination: build-log

  build-mem:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build Release
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: build.log
          destination: build-log

  build-cov:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build Release
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: build.log
          destination: build-log

  build-perf:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build Release
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: build.log
          destination: build-log

  unit-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Unit Test
          command: |
            cd ~/cygnus
            source sourceme
            cytest -d tests -a 2>&1 | tee cytest.log
      - store_artifacts:
          path: ~/cygnus/cytest.log
          destination: unit-test-log
  
  warnings:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

  lint:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
  styling:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

  coverage:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

  memory:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

  performance:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

  reports:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

workflows:
  version: 2
  Commit-Test:
    jobs:
      - checkout
      - styling:
          requires:
            - checkout
      - build-release:
          requires:
            - checkout
      - build-cov:
          requires:
            - build-release
      - build-mem:
          requires:
            - build-release
      - build-perf:
          requires:
            - build-release
      - warnings:
          requires:
            - build-release
      - unit-test:
          requires:
            - build-release
      - lint:
          requires:
            - warnings
      - coverage:
          requires:
            - build-cov
      - memory:
          requires:
            - build-mem
      - performance:
          requires:
            - build-perf
      - reports:
          requires:
            - styling
            - warnings
            - unit-test
            - lint
            - coverage
            - memory
            - performance
