version: 2.0

jobs:
  checkout:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/cygnus
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus

  build-release:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/cygnus
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Release Build
          command: |
            cd ~/cygnus
            source sourceme
            cybuild --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: build.log
          destination: build-log

  unit-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Unit Test
          command: |
            cd ~/cygnus
            source sourceme
            cytest -d tests -a 2>&1 | tee cytest.log
      - store_artifacts:
          path: ~/cygnus/cytest.log
          destination: unit-test-log
  
  warnings:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Compiler Warnings on strict mode
          command: |
              cd ~/cygnus
              source sourceme
              cybuild --strict --release 2>&1 | tee build.log
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: ~/cygnus/build.log
          destination: Build log
      - store_artifacts:
          path: ~/cygnus/reports/warnings/warns
          destination: Warnings

  lint:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Run
          command: echo "Disabled"

  styling:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

  coverage:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Coverage Run
          command: |
              cd ~/cygnus
              source sourceme
              cytest -a -d tests --coverage
      - persist_to_workspace:
          root: ~/
          paths:
            - cygnus
      - store_artifacts:
          path: ~/cygnus/reports/cov
          destination: Coverage data

  memory:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

  performance:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - attach_workspace:
          at: ~/

  reports:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: echo "Report generation step."

workflows:
  version: 2
  Commit-Test:
    jobs:
      - checkout
      - styling:
          requires:
            - checkout
      - build-release:
          requires:
            - checkout
      - warnings:
          requires:
            - build-release
      - unit-test:
          requires:
            - build-release
      - lint:
          requires:
            - warnings
      - coverage:
          requires:
            - build-release
      - memory:
          requires:
            - build-release
      - performance:
          requires:
            - build-release
      - reports:
          requires:
            - styling
            - unit-test
            - lint
            - coverage
            - memory
            - performance
