FROM gcc:9.2.0

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y doxygen
RUN apt-get install -y graphviz
RUN apt-get install -y lcov
RUN apt-get install -y python3.7
RUN apt-get install -y valgrind
