.TH "CyStream" 1 "Sun Sep 22 2019" "Version 1.0b" "Cygnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CyStream
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBopen\fP (const std::string &filename, std::ios_base::openmode mode=std::ios_base::in|std::ios_base::out)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file CyStream\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cygnus from the source code\&.
