.TH "Log" 1 "Sun Sep 22 2019" "Version 1.0b" "Cygnus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBD\fP (const std::string &msg)"
.br
.ti -1c
.RI "void \fBE\fP (const std::string &msg)"
.br
.ti -1c
.RI "void \fBI\fP (const std::string &msg)"
.br
.ti -1c
.RI "void \fBW\fP (const std::string &msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Log\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Cygnus from the source code\&.
