#!/bin/bash

source cmdline.bash    # command line parser

declare -a valid_list
declare -a valid_tests
declare -a fail_list

declare OUT_DIR='test_run'
declare TEST_MODE=''
declare FUNC_COUNT=0
declare UNIT_COUNT=0

TEE() {
    echo "" > $1
    while IFS= read line; do
        echo "$line"
        echo "$line" | sed -r -e 's|\x1b\[[;0-9]*m\x1b\[K||g' -e 's/\x1b\[[0-9]+m//g' >> $1
    done
}

GENHTML() {
    genhtml --ignore-errors source reports/coverage/$1/coverage.info --output-directory reports/coverage/$1/html --demangle-cpp --css-file tools/coverage.css -t "$1 coverage" --legend --rc genhtml_hi_limit=98 --rc genhtml_med_limit=80 > reports/coverage/$1/genhtml.log 2> /dev/null
    egrep -A 1 'lines\.\.\.\.\.\.:' reports/coverage/$1/genhtml.log
}

OPTION['-a']='value:string,metavar:dir,help:run all tests from <dir>'
OPTION['-f']='value:string,metavar:dir,without:-a,help:run functional tests only from <dir>'
OPTION['-o']='value:string,metavar:dir,help:output directory of test run'
OPTION['-r']='value:bool,help:reflog update'
OPTION['-u']='value:string,metavar:dir,without:-a,help:run unit tests only from <dir>'
OPTION['--coverage']='value:bool,eval:TEST_MODE=coverage,help:run coverage tests'
OPTION['--mem-check']='value:bool,eval:TEST_MODE=mem-check,help:run mem-check tests'
OPTION['--perf']='value:bool,eval:TEST_MODE=perf,help:run mem-check tests'
OPTION['--sanitize']='value:bool,eval:TEST_MODE=sanitize,help:run sanitization tests'
OPTION['POS']='dest:test_list,count:0+'

validateTests() {
    if [[ ${VALUES['-a']} ]]; then
        test -d ${VALUES['-a']} || LOG EE "directory \`${VALUES['-a']}' does not exit";
        valid_tests=$(find ${VALUES['-a']} -type f -name "*.cyt" | xargs realpath)
    elif [[ ${VALUES['-f']} ]]; then
        test -d ${VALUES['-f']} || LOG EE "directory \`${VALUES['-f']}' does not exit";
        valid_tests=$(find ${VALUES['-f']} -type f -path "*func*.cyt" | xargs realpath)
    elif [[ ${VALUES['-u']} ]]; then
        test -d ${VALUES['-u']} || LOG EE "directory \`${VALUES['-u']}' does not exit";
        valid_tests=$(find ${VALUES['-u']} -type f -path "*unit*.cyt" | xargs realpath)
    else
        for test in ${VALUES["test_list"]}; do
            abs_test=$(realpath $test)
            if [[ $abs_test =~ unit.*\.cyt || $abs_test =~ func.*\.cyt && -a $abs_test ]]; then
                valid_tests+=" $abs_test"
            else
                LOG W "[invalid testcase] $abs_test"
                continue
            fi
        done
    fi
    if [[ -z $valid_tests ]]; then
      LOG EE "no valid testcases found"
    fi
}

makeRunDir(){
    local testcase_dir=$1
    local testcase=$2
    local test_out=$OUT_DIR/`dirname $testcase`
    rm -rf $test_out
    mkdir -p $test_out || return 1
    ln -rs $testcase_dir/`dirname $testcase`/* $test_out/ || return 1
}

runFuncTest() {
    {
    for i in ${!CASE[@]}; do
        echo "[CASE $((i+1))] $(echo ${CASE[$i]} | sed "s|$CYGNUS|cygnus|")"
        $tool ${CASE[$i]} | sed 's/.*/>   &/' || return 1
        echo
    done
    } 2>&1 > TESTLOG
}

runUnitTest() {
    gen-make -i $CYGNUS_HOME/include -i $CYGNUS_HOME/src -i$CYGNUS_HOME/tests/utils/include -s $CYGNUS_HOME/src -s $CYGNUS_HOME/tests/utils/src unit.cc || return 1
    #make --no-print-directory $TEST_MODE 2>&1 | TEE make.log 
    {
    $tool ./unit | sed -e '/\[CASE/! s/.*/>   &/' -e ' 2,$ s/\[CASE/\n[CASE/' || return 1
    echo
    } 2>&1 > TESTLOG 
}

runTest() {
    local test=$1
    local status=0
    declare -A DIFFS
    declare -a SORT_OUTPUT=()

    if [[ $test =~ func.*cyt ]]; then
        local testcase_dir=${test%/func*cyt}
        local testcase=${test#$testcase_dir/}
        FUNC_COUNT=$((FUNC_COUNT + 1))
        makeRunDir $testcase_dir $testcase
        cd $OUT_DIR/`dirname $testcase`
        echo "[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt] $testcase"
        source `basename $1`
        runFuncTest $testcase || status=1
    else
        local testcase_dir=${test%/unit*cyt}
        local testcase=${test#$testcase_dir/}
        UNIT_COUNT=$((UNIT_COUNT + 1))
        makeRunDir $testcase_dir $testcase
        cd $OUT_DIR/`dirname $testcase`
        echo "[TESTCASE $((FUNC_COUNT + UNIT_COUNT))/$tc_cnt] $testcase"
        source `basename $1`
        runUnitTest $testcase || status=1
    fi

    #---------------#
    #  SORT_OUTPUT  #
    #---------------#
    if [[ $((${#SORT_OUTPUT[@]}%3)) -eq 0 ]]; then
        for i in $(eval echo {0..$((${#SORT_OUTPUT[@]}-1))..3}); do
            local case=${SORT_OUTPUT[$i]}
            local begin=${SORT_OUTPUT[$((i+1))]}
            local end=${SORT_OUTPUT[$((i+2))]}
            local line_cnt=0
            local buff=""
            local modify=""

            while IFS= read line; do
                line_cnt=$((line_cnt + 1))
                if [[ $line =~ ^\[$case\] ]]; then
                    echo "$line"
                    modify="yes"
                    line_cnt=0
                    continue
                fi

                if [[ $modify ]] && [[ $line == "" ]]; then
                    printf "%b" "$buff" | sort
                    echo "$line"
                    buff=""
                    modify=""
                    continue
                fi

                if [[ $modify ]] && [[ $line_cnt -eq $end ]]; then
                    printf "$buff$line" | sort
                    buff=""
                    modify=""
                    continue
                fi

                if [[ $modify ]] && [[ $line_cnt -ge $begin ]]; then
                    buff+=$line'\n'
                    continue
                fi

                printf "%s\n" "$line"
            done < TESTLOG > TESTLOG.tmp
            mv TESTLOG.tmp TESTLOG
        done
    else
        LOG E "Directive SORT_OUTPUT has ${#SORT_OUTPUT[@]} elements, it should be multiple of 3"
        status=1
    fi

    for ref in ${!DIFFS[@]}; do
        diff -N --color=always $ref ${DIFFS[$ref]}
        if [[ $? -ne 0 ]]; then
            status=1
            if [[ ${VALUES['-r']} ]]; then
                cp ${DIFFS[$ref]} $ref
                echo "$ref updated"
            fi
        fi
    done

    if [[ $status -eq 0 ]]; then
        echo "status: PASS"
    else
        echo "status: FAIL"
        fail_cnt=$((fail_cnt + 1))
        fail_list+=($testcase)
    fi

    case $TEST_MODE in
        mem-check)
            if [[ $(egrep -c "ERROR SUMMARY: 0 errors" valgrind.out) -ne 1 ]]; then
                sed -nr -e 's/^=+[0-9]+=+ //' -e '/HEAP SUMMARY/,/LEAK SUMMARY/ p' valgrind.out | sed -e '/HEAP SUMMARY:\|LEAK SUMMARY:/,/^$/ d'  | \
                while IFS= read line; do
                    # Just a hack
                    if [[ $line == "All heap blocks were freed -- no leaks are possible" ]]; then
                        break
                    fi
                    if [[ $line == "" ]]; then
                        checksum=$(echo $error | md5sum | egrep -o "[0-Z]+")
                        echo "CHECKSUM: $checksum" >> mem.err
                        echo -e "$error" >> mem.err
                        error=""
                        continue
                    fi
                    error="    ${line/#   /}\n$error"
                done
                echo "mem-error: $(egrep -c "CHECKSUM: " mem.err)"
            fi
            ;;
        perf)
            callgrind_annotate --threshold=100 callgrind.out | egrep "$CYGNUS_HOME/src/" | gen-perf > TESTPERF
            perf-diff REFPERF TESTPERF | tee perf.diff
            ;;
    esac
    cd - > /dev/null
}

main() {
    mkdir -p logs
    parseCmdLine $@
    {
    OUT_DIR=${VALUES['-o']:-$OUT_DIR} 
    validateTests
    if [[ $test_out == $OUT_DIR ]]; then
        LOG EE "test directory and out directory cannot be same"
    fi
    echo "    OUT_DIR: $OUT_DIR"

    tc_cnt=0
    for test in $valid_tests; do
        tc_cnt=$((tc_cnt + 1))
    done
    echo -e "\nGenerated Testcase: $tc_cnt"

    #-----------#
    #  Pre Run  #
    #-----------#
    case $TEST_MODE in
        coverage)
            CYGNUS=$CYGNUS_HOME/build/bin/coverage/cygnus-coverage
            OUT_DIR="$OUT_DIR/coverage"
            mkdir -p reports/coverage
            ;;
        mem-check)
            CYGNUS=$CYGNUS_HOME/build/bin/memory/cygnus-memory
            OUT_DIR="$OUT_DIR/mem-check"
            mkdir -p reports/mem-check
            tool="valgrind --track-origins=yes --errors-for-leak-kinds=all --show-leak-kinds=all --leak-check=full --log-file=valgrind.out"
            ;;
        perf)
            CYGNUS=$CYGNUS_HOME/build/bin/perf/cygnus-perf
            OUT_DIR="$OUT_DIR/perf"
            mkdir -p reports/perf
            tool="valgrind --tool=callgrind --callgrind-out-file=callgrind.out"
            ;;
        sanitize)
            CYGNUS=$CYGNUS_HOME/build/bin/sanitize/cygnus-sanitize
            OUT_DIR="$OUT_DIR/sanitize"
            mkdir -p reports/sanitize
            ;;
        *)
            CYGNUS=$CYGNUS_HOME/build/bin/cygnus
            ;;
    esac

    if [[ ${VALUES['-a']} || ${VALUES['-f']} ]] && [[ ! -x $CYGNUS ]]; then
        LOG EE "$CYGNUS does not exist"
    fi
    rm -rf reports/func reports/unit
    mkdir -p reports/func reports/unit
    export fail_cnt=0

    #-----------#
    #    Run    #
    #-----------#
    for test in $valid_tests; do
        ret=0
        echo
        runTest $test
    done

    #-----------#
    # Post Run  #
    #-----------#
    case $TEST_MODE in
        coverage)
            if [[ $FUNC_COUNT -gt 0 ]]; then
                echo -e "\nFunctional Coverage:"
                mkdir -p reports/coverage/func
                rm -f reports/coverage/func/coverage.info
                for dir in $(find build/obj/coverage -mindepth 1 -type d); do
                    lcov --gcov-tool=gcov-7 -c -b src/${dir#build/obj/coverage/} -d $dir -d include --no-external -q >> reports/coverage/func/coverage.info 2> /dev/null
                done
                GENHTML func
            fi

            if [[ $UNIT_COUNT -gt 0 ]]; then
                echo -e "\nUnit Coverage:"
                mkdir -p reports/coverage/unit
                rm -f reports/coverage/unit/coverage.info
                for dir in $(find src -mindepth 1 -type d); do
                    lcov --gcov-tool=gcov-7 -b $dir -c -d $OUT_DIR -d include --no-external -q >> reports/coverage/unit/coverage.info 2> /dev/null
                done

                # Put missing files in coverage.info when all testcases in directory run
                if [[ ${VALUES['-a']} ]]; then
                    mkdir /tmp/cygnus_tmp -p
                    find include src -regex ".*\.cc\|.*\.h\|.*\.tcc" | egrep -v "main.cc|cymem.cc" | sort -u | xargs realpath > /tmp/cygnus_tmp/all_files
                    egrep "SF:" reports/coverage/unit/coverage.info  | sed 's/SF://' | sort -u > /tmp/cygnus_tmp/covered_files
                    comm -23 /tmp/cygnus_tmp/all_files /tmp/cygnus_tmp/covered_files > /tmp/cygnus_tmp/uncovered_files
                    {
                    for file in `cat /tmp/cygnus_tmp/uncovered_files`; do
                        echo "SF:$file"
                        cat -ns $file | sed -r -e 's/^[ ]+//' -e 's/\t/ /g' | egrep -v "^[0-9]+ $|[0-9]+ (/|#)|[0-9]+  \*" | egrep -o "^[0-9]+" | sed 's/.*/DA:&,0/'
                        echo "end_of_record"
                    done
                    } >> reports/coverage/unit/coverage.info
                fi

                # remove unit.cc from coverage.info
                sed -i '/unit.cc$/,/end_of_record/ d' reports/coverage/unit/coverage.info

                GENHTML unit
            fi

            if [[ ${VALUES['-a']} ]]; then
                echo -e "\nComplete Coverage:"
                mkdir -p reports/coverage/comp
                lcov --gcov-tool=gcov-7 -b src/base -c -d build/obj/coverage -d $OUT_DIR -d include --no-external -o reports/coverage/comp/coverage.info -q 2> /dev/null

                # remove unit.cc from coverage.info
                sed -i '/unit.cc$/,/end_of_record/ d' reports/coverage/comp/coverage.info

                GENHTML comp
            fi
            ;;
        mem-check)
            rm -rf reports/mem-check
            if [[ ${VALUES['-a']} || ${VALUES['-f']} ]]; then
                mkdir -p reports/mem-check/func
                find $OUT_DIR/func -name "mem.err" | xargs egrep -h "CHECKSUM" | sort -u | wc -l >> reports/mem-check/func/errors
            fi
            if [[ ${VALUES['-a']} || ${VALUES['-u']} ]]; then
                mkdir -p reports/mem-check/unit
                find $OUT_DIR/unit -name "mem.err" | xargs egrep -h "CHECKSUM" | sort -u | wc -l >> reports/mem-check/unit/errors
            fi
            echo "    Memory Errors: $(find $OUT_DIR/unit $OUT_DIR/func -name "mem.err" | xargs egrep -h "CHECKSUM" | sort -u | wc -l)"
            ;;
        perf)
            ;;
        *)
    esac

    #-----------#
    #  Summary  #
    #-----------#
    if [[ ${#fail_list} -ne 0 ]]; then
        echo -e "\nFAILED:"
        for fail in ${fail_list[@]}; do
            echo "$fail"
        done
        SET_ERROR 1
    fi
    echo -e "\nSummary:"
    echo "    RUN:  $tc_cnt"
    echo "    PASS: $((tc_cnt - fail_cnt))"
    echo "    FAIL: $fail_cnt"
    RETURN_ERROR
    } | TEE logs/cyregress${TEST_MODE:+-$TEST_MODE}.log
    return ${PIPESTATUS[0]}
}

main $@
EXIT $?
