#!/usr/bin/python3.6

import argparse
import os
import subprocess
import sys

######################## CLASS ########################
class IO:
    tag_id = {
                "C":"CMD",      # Command tag
                "E":"ERROR",    # Error tag
                "F":"FAIL",     # Fail tag
                "I":"INFO",     # Info tag
                "W":"WARN"      # Warning tag
            }

    @staticmethod
    def log(mode, msg):
        tag = IO.tag_id.get(mode)
        if(tag == None):
            raise Exception("unknown mode \`" + mode + "' specified")
        
        print("[%s] %s" %(tag, msg))

    @staticmethod
    def cmdOut(msg):
        for line in msg.split('\n'):
            print(" >  " + line)

    @staticmethod
    def fileAppend(fd, msg, line_end='\n'):
        print(msg, end=line_end, file=fd)

class Args:
    __parser = argparse.ArgumentParser()

    def __init__(self):
        self.__parser.add_argument("file", help="genrate Makefile for this file")
        self.__parser.add_argument("-d", dest="cDir", metavar="dir", default=".", help="alternate location of file if not current directory")
        self.__parser.add_argument("-i", dest="incDir", metavar="dir", action="append", required=True, help="path of include directory")

    def parse(self):
        return self.__parser.parse_args()


######################### FUNCTIONS ########################
def printMakefile(opt, target, h_deps, cc_deps):
    o_deps = []
    makefile = open("Makefile", "w")

    IO.fileAppend(makefile, "############# Configs #############")
    
    # Common rules
    IO.fileAppend(makefile, "CY_COMP = g++ $(INC)\n")
    IO.fileAppend(makefile, "INC = ", '')
    for i in opt.incDir:
        IO.fileAppend(makefile, " \\\n    -I " + i, '')
    IO.fileAppend(makefile,'\n')

    print("OBJ_DIR := " + os.path.relpath("obj", opt.cDir[opt.cDir.rfind("unit/"):]) + "\n", file = makefile)  
    IO.fileAppend(makefile, "############# Targets #############")
    print("all: $(OBJ_DIR) " + target + "\n", file = makefile)
    
    # Target rules
    print(target + ": ", end = '', file = makefile)
    #o_deps.append(cc_deps.pop(0))
    for dep in cc_deps:
        print("dep: " + dep)
        ind = dep.find("/src")
        if(ind > 0):
            obj = "$(OBJ_DIR)" + dep[ind+4:].replace(".cc", ".o")
        else:
            obj = dep.replace(".cc", ".o")
        o_deps.append(obj)
        print(obj, end = ' ', file = makefile)

    print("", file = makefile)
    print("\t$(CY_COMP) -o $@ $^\n", file = makefile)

    for dep in o_deps:
        print(dep + ": " + cc_deps.pop(0) + " " + h_deps.pop(0), file = makefile)
        print("\t$(CY_COMP) -c $< -o $@\n", file = makefile)

    print("$(OBJ_DIR):", file = makefile)
    print("\tmkdir $@\n", file = makefile)

    # Clean target
    print("clean:\n\trm -rf ", end='', file=makefile)
    for dep in o_deps:
        print(dep, end=' ', file=makefile)
    print(target, file=makefile)


######################## MAIN ########################
def main():
    args = Args()
    opt = args.parse()
    h_deps = []
    cc_deps = []
    
    os.chdir(opt.cDir)
    
    t = []
    for path in opt.incDir:
        if not os.path.isabs(path):
            t.append(os.path.relpath(path, opt.cDir))
        else:
            t.append(path)
    opt.incDir = t

    # Run command
    cmd = ["g++", "-MM"]
    for i in opt.incDir:
        cmd.append("-I" + i)
    cmd.append(opt.file)
    IO.log("C", ' '.join(cmd))
    proc = subprocess.Popen(cmd, stdout = subprocess.PIPE, stderr = subprocess.STDOUT)
    stdout, stderr = proc.communicate()

    if(proc.returncode):
        IO.cmdOut(stdout.decode("utf-8"))
        IO.log("F", "command failed: " + ' '.join(cmd))
        return 1
    
    line = stdout.decode("utf-8").split(' ')
    target = line.pop(0).strip(".o:")
    cc_deps.append(line.pop(0)) # this file is test.cc
    h_deps.append(line.pop(0))  # this file is test.h
    
    for dep in line:
        dep = dep.strip('\n');
        if dep == "\\":
            continue
        h_deps.append(dep)
        cc_deps.append(dep.replace("include", "src").replace(".h", ".cc"))

    printMakefile(opt, target, h_deps, cc_deps)

if __name__ == "__main__":
    ret = main()
    sys.exit(ret)
