#!/bin/bash

CONFIG=.doxygen/config

mv docs docs.bk

mkdir docs
mkdir -p reports/docs

doxygen $CONFIG
undoc=`cat reports/docs/undocumented | wc -l`

diff -qr docs docs.bk
if [[ $? -eq 0 ]]; then
    doc_diff=no
else
    doc_diff=yes
fi

rm -rf docs.bk

echo "Undocumented: $undoc"
echo "Need to update docs: $doc_diff"
