#!/bin/bash

CONFIG=.doxygen/config

mkdir -p docs reports/docs

doxygen $CONFIG
sed -i '/\(variable\)/ d' reports/docs/undoc
cat reports/docs/undoc
undoc=$(cat reports/docs/undoc | wc -l)

tar fu docs.tar docs

if [[ $(git status docs.tar | tail -1) == "nothing to commit, working tree clean" ]]; then
    doc_diff=no
else
    doc_diff=yes
fi

if [[ $1 != "-r" ]]; then
    rm -rf docs
fi

echo "Undocumented: $undoc" | tee reports/docs/status
echo "Need to update docs: $doc_diff" | tee -a reports/docs/status
