#!/bin/bash

declare EXITCODE=0

adder() {
    local sum=0
    while [[ $1 ]]; do
        sum=$((sum+$1))
        shift
    done
    echo $sum
}

covReport() {
    local func_cov=-1
    local unit_cov=-1

    test -f reports/coverage/func/html/index.html && func_cov=$(egrep -m 1 "headerCovTableEntryHi" reports/coverage/func/html/index.html | sed -r 's/[^0-9.]//g')
    test -f reports/coverage/unit/html/index.html && unit_cov=$(egrep -m 1 "headerCovTableEntryHi" reports/coverage/unit/html/index.html | sed -r 's/[^0-9.]//g')
    
    if [[ $func_cov -lt 100 || $unit_cov -lt 100 ]]; then
        EXITCODE=1
    fi
    
    echo "Coverage Report::"
    echo "    Funtional Coverage: ${func_cov}%"
    echo "    Unit Coverage: ${func_cov}%"
    echo
}

docsReport() {
    local undoc_count=$(cat reports/docs/undoc | wc -l)
    local need_update=$(egrep -o "yes|no" reports/docs/status)

    if [[ $undoc_count -gt 0 || $need_update == 'yes' ]]; then
        EXITCODE=1
    fi

    echo "DOCS::"
    echo "    Needs Update: $need_update"
    echo "    Undocumented: $undoc_count"
    echo
}

lintReport() {
    local lint_error=$($(egrep 'linterror: ' reports/lint.log | egrep -v 'Cppcheck does not need standard library headers to get proper results' | wc -l))

    if [[ $lint_error -gt 0 ]]; then
        EXITCODE=1
    fi

    echo "Lint Report::"
    echo "    Errors: $lint_error"
    echo
}

memReport() {
    local func_error=-1
    local unit_error=-1

    test -f reports/mem-check/func/errors && func_error=$(adder $(egrep -o "[0-9] errors" reports/mem-check/func/errors | sed 's/ errors//'))
    test -f reports/mem-check/unit/errors && unit_error=$(adder $(egrep -o "[0-9] errors" reports/mem-check/unit/errors | sed 's/ errors//'))

    if [[ $func_error -ne 0 || $unit_error -ne 0 ]]; then
        EXITCODE=1
    fi

    echo "Memory Report::"
    echo "    Functional: $func_error"
    echo "    Unit: $unit_error"
    echo
}

perfReport() {
    local func_perf=$(find test_run/perf/func -name "testfail" | wc -l )
    local unit_perf=$(find test_run/perf/unit -name "testfail" | wc -l )

    echo "Performace Report::"
    if [[ $func_perf -eq 0 ]]; then
        echo "    Functional: PASS"
    else
        EXITCODE=1
        echo "    Functional: FAIL"
    fi
    if [[ $unit_perf -eq 0 ]]; then
        echo "    Unit: PASS"
    else
        EXITCODE=1
        echo "    Unit: FAIL"
    fi
    echo
}

releaseTestReport() {
    EXITCODE=1
    echo "Test Cases::"
    echo "    Functional Test: -1"
    echo "    Unit Test: -1"
    echo
}

sanitizationReport() {
    echo "Sanitization Report::"
    if [[  $(find test_run/sanitize/func -name "run.log" | xargs egrep -c "ERROR: ") -eq 0 ]]; then
        echo "    Functioncal: PASS"
    else
        EXITCODE=1
        echo "    Functional: FAIL"
    fi
    if [[  $(find test_run/sanitize/unit -name "run.log" | xargs egrep -c "ERROR: ") -eq 0 ]]; then
        echo "    Unit: PASS"
    else
        EXITCODE=1
        echo "    Unit: FAIL"
    fi
    echo
}

styleReport() {
    local errors=-1

    test -f reports/style.log && errors=$(egrep -c "error: " reports/style.log)
    if [[ $errors -gt 0 ]]; then
        EXITCODE=1
    fi

    echo "Style Report::"
    echo "    errors: $errors"
    echo

}

warnReport() {
    local debug_warn=-1
    local release_warn=-1

    test -f reports/warnings/debug-errors && debug_warn=$(egrep -c "warning: " reports/warnings/debug-errors) 
    test -f reports/warnings/release-errors && release_warn=$(egrep -c "warning: " reports/warnings/release-errors)
    
    if [[ $debug_warn -ne 0 || $release_warn -ne 0 ]]; then
        EXITCODE=1
    fi
    echo "Compiler Warnings::"
    echo "    Debug: $debug_warn"
    echo "    Release: $release_warn"
    echo
}

main() {
    covReport
    docsReport
    lintReport
    memReport
    perfReport
    releaseTestReport
    sanitizationReport
    styleReport
    warnReport
    exit $EXITCODE
}

main $@
