name: CI

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        source sourceme
        cybuild
        
  job2:
    runs-on: [ubuntu-latest]
    container: aloknigam247/cygnus
    steps:
      - name: Build
        run: |
          source sourceme
          cybuild
          
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: ./.docker/actions@v1
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
